---
- name: anthos-gke
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    cluster_hostname: admin-cluster
    instances: 26
    ip: 10.96.100.10
    netmask: 255.255.255.0
    gateway: 10.96.100.1
    dns:
    - 8.8.8.8
    - 8.8.4.4
    - 1.1.1.1
    tod:
    - 0.ubuntu.pool.ntp.org
    - 1.ubuntu.pool.ntp.org
  roles:
    - static
